//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.31 at 10:07:36 PM BRT 
//


package com.hogemann.stamp.xml.amazon.simpledb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ItemNamesSizeBytes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttributeNameCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttributeNamesSizeBytes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttributeValueCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttributeValuesSizeBytes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemCount",
    "itemNamesSizeBytes",
    "attributeNameCount",
    "attributeNamesSizeBytes",
    "attributeValueCount",
    "attributeValuesSizeBytes",
    "timestamp"
})
@XmlRootElement(name = "DomainMetadataResult", namespace = "http://sdb.amazonaws.com/doc/2009-04-15/")
public class DomainMetadataResult {

    @XmlElement(name = "ItemCount", namespace = "http://sdb.amazonaws.com/doc/2009-04-15/", required = true)
    protected String itemCount;
    @XmlElement(name = "ItemNamesSizeBytes", namespace = "http://sdb.amazonaws.com/doc/2009-04-15/", required = true)
    protected String itemNamesSizeBytes;
    @XmlElement(name = "AttributeNameCount", namespace = "http://sdb.amazonaws.com/doc/2009-04-15/", required = true)
    protected String attributeNameCount;
    @XmlElement(name = "AttributeNamesSizeBytes", namespace = "http://sdb.amazonaws.com/doc/2009-04-15/", required = true)
    protected String attributeNamesSizeBytes;
    @XmlElement(name = "AttributeValueCount", namespace = "http://sdb.amazonaws.com/doc/2009-04-15/", required = true)
    protected String attributeValueCount;
    @XmlElement(name = "AttributeValuesSizeBytes", namespace = "http://sdb.amazonaws.com/doc/2009-04-15/", required = true)
    protected String attributeValuesSizeBytes;
    @XmlElement(name = "Timestamp", namespace = "http://sdb.amazonaws.com/doc/2009-04-15/", required = true)
    protected String timestamp;

    /**
     * Gets the value of the itemCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCount() {
        return itemCount;
    }

    /**
     * Sets the value of the itemCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCount(String value) {
        this.itemCount = value;
    }

    /**
     * Gets the value of the itemNamesSizeBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemNamesSizeBytes() {
        return itemNamesSizeBytes;
    }

    /**
     * Sets the value of the itemNamesSizeBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemNamesSizeBytes(String value) {
        this.itemNamesSizeBytes = value;
    }

    /**
     * Gets the value of the attributeNameCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeNameCount() {
        return attributeNameCount;
    }

    /**
     * Sets the value of the attributeNameCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeNameCount(String value) {
        this.attributeNameCount = value;
    }

    /**
     * Gets the value of the attributeNamesSizeBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeNamesSizeBytes() {
        return attributeNamesSizeBytes;
    }

    /**
     * Sets the value of the attributeNamesSizeBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeNamesSizeBytes(String value) {
        this.attributeNamesSizeBytes = value;
    }

    /**
     * Gets the value of the attributeValueCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeValueCount() {
        return attributeValueCount;
    }

    /**
     * Sets the value of the attributeValueCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeValueCount(String value) {
        this.attributeValueCount = value;
    }

    /**
     * Gets the value of the attributeValuesSizeBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeValuesSizeBytes() {
        return attributeValuesSizeBytes;
    }

    /**
     * Sets the value of the attributeValuesSizeBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeValuesSizeBytes(String value) {
        this.attributeValuesSizeBytes = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

}
