//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.31 at 10:07:36 PM BRT 
//


package com.hogemann.stamp.xml.amazon.simpledb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hogemann.stamp.xml.amazon.simpledb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hogemann.stamp.xml.amazon.simpledb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DomainMetadataResult }
     * 
     */
    public DomainMetadataResult createDomainMetadataResult() {
        return new DomainMetadataResult();
    }

    /**
     * Create an instance of {@link DeleteableItem }
     * 
     */
    public DeleteableItem createDeleteableItem() {
        return new DeleteableItem();
    }

    /**
     * Create an instance of {@link SelectResponse }
     * 
     */
    public SelectResponse createSelectResponse() {
        return new SelectResponse();
    }

    /**
     * Create an instance of {@link Select }
     * 
     */
    public Select createSelect() {
        return new Select();
    }

    /**
     * Create an instance of {@link DeleteDomainResponse }
     * 
     */
    public DeleteDomainResponse createDeleteDomainResponse() {
        return new DeleteDomainResponse();
    }

    /**
     * Create an instance of {@link ListDomainsResponse }
     * 
     */
    public ListDomainsResponse createListDomainsResponse() {
        return new ListDomainsResponse();
    }

    /**
     * Create an instance of {@link PutAttributes }
     * 
     */
    public PutAttributes createPutAttributes() {
        return new PutAttributes();
    }

    /**
     * Create an instance of {@link SelectResult }
     * 
     */
    public SelectResult createSelectResult() {
        return new SelectResult();
    }

    /**
     * Create an instance of {@link BatchDeleteAttributesResponse }
     * 
     */
    public BatchDeleteAttributesResponse createBatchDeleteAttributesResponse() {
        return new BatchDeleteAttributesResponse();
    }

    /**
     * Create an instance of {@link BatchPutAttributes }
     * 
     */
    public BatchPutAttributes createBatchPutAttributes() {
        return new BatchPutAttributes();
    }

    /**
     * Create an instance of {@link ReplaceableItem }
     * 
     */
    public ReplaceableItem createReplaceableItem() {
        return new ReplaceableItem();
    }

    /**
     * Create an instance of {@link DeleteAttributes }
     * 
     */
    public DeleteAttributes createDeleteAttributes() {
        return new DeleteAttributes();
    }

    /**
     * Create an instance of {@link UpdateCondition }
     * 
     */
    public UpdateCondition createUpdateCondition() {
        return new UpdateCondition();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link GetAttributes }
     * 
     */
    public GetAttributes createGetAttributes() {
        return new GetAttributes();
    }

    /**
     * Create an instance of {@link PutAttributesResponse }
     * 
     */
    public PutAttributesResponse createPutAttributesResponse() {
        return new PutAttributesResponse();
    }

    /**
     * Create an instance of {@link GetAttributesResponse }
     * 
     */
    public GetAttributesResponse createGetAttributesResponse() {
        return new GetAttributesResponse();
    }

    /**
     * Create an instance of {@link DeleteDomain }
     * 
     */
    public DeleteDomain createDeleteDomain() {
        return new DeleteDomain();
    }

    /**
     * Create an instance of {@link BatchDeleteAttributes }
     * 
     */
    public BatchDeleteAttributes createBatchDeleteAttributes() {
        return new BatchDeleteAttributes();
    }

    /**
     * Create an instance of {@link DeleteAttributesResponse }
     * 
     */
    public DeleteAttributesResponse createDeleteAttributesResponse() {
        return new DeleteAttributesResponse();
    }

    /**
     * Create an instance of {@link ReplaceableAttribute }
     * 
     */
    public ReplaceableAttribute createReplaceableAttribute() {
        return new ReplaceableAttribute();
    }

    /**
     * Create an instance of {@link DomainMetadataResponse }
     * 
     */
    public DomainMetadataResponse createDomainMetadataResponse() {
        return new DomainMetadataResponse();
    }

    /**
     * Create an instance of {@link DomainMetadata }
     * 
     */
    public DomainMetadata createDomainMetadata() {
        return new DomainMetadata();
    }

    /**
     * Create an instance of {@link ListDomains }
     * 
     */
    public ListDomains createListDomains() {
        return new ListDomains();
    }

    /**
     * Create an instance of {@link BatchPutAttributesResponse }
     * 
     */
    public BatchPutAttributesResponse createBatchPutAttributesResponse() {
        return new BatchPutAttributesResponse();
    }

    /**
     * Create an instance of {@link CreateDomain }
     * 
     */
    public CreateDomain createCreateDomain() {
        return new CreateDomain();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link GetAttributesResult }
     * 
     */
    public GetAttributesResult createGetAttributesResult() {
        return new GetAttributesResult();
    }

    /**
     * Create an instance of {@link ResponseMetadata }
     * 
     */
    public ResponseMetadata createResponseMetadata() {
        return new ResponseMetadata();
    }

    /**
     * Create an instance of {@link ListDomainsResult }
     * 
     */
    public ListDomainsResult createListDomainsResult() {
        return new ListDomainsResult();
    }

    /**
     * Create an instance of {@link CreateDomainResponse }
     * 
     */
    public CreateDomainResponse createCreateDomainResponse() {
        return new CreateDomainResponse();
    }

}
